// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_process from "./routes/api/process.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $shared_shareId_ from "./routes/shared/[shareId].tsx";
import * as $shared_index from "./routes/shared/index.tsx";
import * as $ArcDiagramViz from "./islands/ArcDiagramViz.tsx";
import * as $CircularNetworkGraph from "./islands/CircularNetworkGraph.tsx";
import * as $ConversationList from "./islands/ConversationList.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DashboardIsland from "./islands/DashboardIsland.tsx";
import * as $EmojimapViz from "./islands/EmojimapViz.tsx";
import * as $ForceDirectedGraph from "./islands/ForceDirectedGraph.tsx";
import * as $HomeIsland from "./islands/HomeIsland.tsx";
import * as $MarkdownMakerDrawer from "./islands/MarkdownMakerDrawer.tsx";
import * as $MobileHistoryMenu from "./islands/MobileHistoryMenu.tsx";
import * as $ShareButton from "./islands/ShareButton.tsx";
import * as $SharedConversationLoader from "./islands/SharedConversationLoader.tsx";
import * as $UploadIsland from "./islands/UploadIsland.tsx";
import * as $VisualizationSelector from "./islands/VisualizationSelector.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/process.ts": $api_process,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/shared/[shareId].tsx": $shared_shareId_,
    "./routes/shared/index.tsx": $shared_index,
  },
  islands: {
    "./islands/ArcDiagramViz.tsx": $ArcDiagramViz,
    "./islands/CircularNetworkGraph.tsx": $CircularNetworkGraph,
    "./islands/ConversationList.tsx": $ConversationList,
    "./islands/Counter.tsx": $Counter,
    "./islands/DashboardIsland.tsx": $DashboardIsland,
    "./islands/EmojimapViz.tsx": $EmojimapViz,
    "./islands/ForceDirectedGraph.tsx": $ForceDirectedGraph,
    "./islands/HomeIsland.tsx": $HomeIsland,
    "./islands/MarkdownMakerDrawer.tsx": $MarkdownMakerDrawer,
    "./islands/MobileHistoryMenu.tsx": $MobileHistoryMenu,
    "./islands/ShareButton.tsx": $ShareButton,
    "./islands/SharedConversationLoader.tsx": $SharedConversationLoader,
    "./islands/UploadIsland.tsx": $UploadIsland,
    "./islands/VisualizationSelector.tsx": $VisualizationSelector,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
